// <auto-generated />
namespace BookBlogProject.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateMail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateMail));
        
        string IMigrationMetadata.Id
        {
            get { return "202304142114222_updateMail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
